# Generated by Django 4.2.9 on 2024-01-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='ghjk', upload_to='pics'),
            preserve_default=False,
        ),
    ]
